# Generated by Django 6.1.2 on 2026-10-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progets',
            name='all_deskrp',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='progets',
            name='photo',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='progets',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
