# Generated by Django 6.1.2 on 2026-10-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projectphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progets',
            name='all_deskrp',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
