# Generated by Django 6.1.2 on 2026-10-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_progets_all_deskrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progets',
            name='all_deskrp',
            field=models.TextField(blank=True, max_length=900),
        ),
    ]
