# Generated by Django 6.1.2 on 2026-10-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Навички',
            },
        ),
        migrations.CreateModel(
            name='Progets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deskrp', models.CharField(max_length=300)),
                ('skills', models.ManyToManyField(to='main.skills')),
            ],
            options={
                'verbose_name': 'Проекти',
            },
        ),
    ]
